version: '3.8'
services:
  mysql:
    image: mysql:8.1.0
    platform: linux/x86_64
    ports: ['3306:3306']
    env_file: ./.env
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    platform: linux/x86_64
    depends_on:
      mysql:
        condition: service_healthy
    image: api
    build:
      context: .
      dockerfile: Dockerfile.native
    env_file: ./.env
    container_name: api
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/$MYSQL_DATABASE
      - spring.datasource.username=$MYSQL_USER
      - spring.datasource.password=$MYSQL_PASSWORD
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.defer-datasource-initialization=true
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    healthcheck:
      test: [ "CMD-SHELL", "curl -X GET localhost:8081/success" ]
      interval: 10s
      timeout: 5s
      retries: 5
